//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY_USER_SUPPLIERS
    {
        public Nullable<int> SUPPLIER_ID { get; set; }
        public Nullable<int> COMPANY_USER_ID { get; set; }
        public int COMPANY_USER_SUPPLIERS_ID { get; set; }
    }
}
