//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY_USERS
    {
        public COMPANY_USERS()
        {
            this.COMPANY_USER_SUPPLIERS = new HashSet<COMPANY_USER_SUPPLIERS>();
        }
    
        public int COMPANY_USER_ID { get; set; }
        public int COMPANY_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string EMAIL { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<int> ROW_VERSION { get; set; }
        public Nullable<int> DB_USER_ID { get; set; }
        public string VALIDATION_CODE { get; set; }
        public Nullable<short> VALIDATION_EMAIL_SENT { get; set; }
        public string PHONE { get; set; }
    
        public virtual ICollection<COMPANY_USER_SUPPLIERS> COMPANY_USER_SUPPLIERS { get; set; }
    }
}
