//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY_SUPPLIERS
    {
        public int COMPANY_ID { get; set; }
        public int SUPPLIER_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> ROW_VERSION { get; set; }
        public Nullable<int> PAYEE_ID { get; set; }
        public Nullable<short> SEND_PASSWORD { get; set; }
        public Nullable<short> IS_TRUSTED_BY_SUPPLIER { get; set; }
    }
}
