//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPA.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
   
    public partial class COMPANY
    {
        public string KEY { get; set; }
        public int COMPANY_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string EMAIL { get; set; }
        public string PHONE1 { get; set; }
        public string PHONE2 { get; set; }
        public string FAX { get; set; }
        public Nullable<int> ROW_VERSION { get; set; }
        public string CODE { get; set; }
        public Nullable<int> PA_REFERENCE { get; set; }
    }
}
