//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbFirstEntities : DbContext
    {
        public DbFirstEntities()
            : base("name=DbFirstEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<COMPANY> COMPANIES { get; set; }
        public DbSet<COMPANY_SUPPLIERS> COMPANY_SUPPLIERS { get; set; }
        public DbSet<PRICE_LIST_ITEM_TYPES> PRICE_LIST_ITEM_TYPES { get; set; }
        public DbSet<COMPANY_USER_SUPPLIERS> COMPANY_USER_SUPPLIERS { get; set; }
        public DbSet<COMPANY_USERS> COMPANY_USERS { get; set; }
        public DbSet<PRICE_AGREEMENT> PRICE_AGREEMENT { get; set; }
        public DbSet<PRICE_AGREEMENT_ADJUSTMENTS> PRICE_AGREEMENT_ADJUSTMENTS { get; set; }
        public DbSet<PRICE_AGREEMENT_MATERIALS> PRICE_AGREEMENT_MATERIALS { get; set; }
        public DbSet<PRICE_LIST> PRICE_LIST { get; set; }
        public DbSet<PRICE_LIST_MATERIALS> PRICE_LIST_MATERIALS { get; set; }
        public DbSet<SUPPLIER> SUPPLIERS { get; set; }
    }
}
