//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRICE_AGREEMENT_ADJUSTMENTS
    {
        public int PRICE_AGREEMENT_ADJUSTMENT_ID { get; set; }
        public Nullable<int> PRICE_AGREEMENT_ID { get; set; }
        public Nullable<short> RECORD_TYPE { get; set; }
        public Nullable<int> RATE_TYPE { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public string RATE_UOM { get; set; }
        public Nullable<System.DateTime> RATE_DATE { get; set; }
        public string CODE { get; set; }
    }
}
