//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WINDEV_CLIENT_VERSION
    {
        public int ID { get; set; }
        public decimal VERSION { get; set; }
        public Nullable<System.DateTime> DATE_UPDATED { get; set; }
        public string URL { get; set; }
    }
}
