//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRICE_LIST_MATERIALS
    {
        public int PRICE_LIST_MATERIAL_ID { get; set; }
        public Nullable<int> PRICE_LIST_ID { get; set; }
        public Nullable<int> ITEM_ID { get; set; }
        public string ITEM_CODE { get; set; }
        public Nullable<int> DIMENSION_ID { get; set; }
        public string DIMENSION_CODE { get; set; }
        public Nullable<int> DIMENSION_CONVERSION { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public string QTY_UOM { get; set; }
        public string MEASURE_TYPE { get; set; }
        public string ITEM_TYPE_GROUP { get; set; }
        public string ITEM_TYPE { get; set; }
        public string PROP_1 { get; set; }
        public string PROP_2 { get; set; }
        public string PROP_3 { get; set; }
        public string PROP_4 { get; set; }
        public string PROP_5 { get; set; }
        public string PROP_6 { get; set; }
        public Nullable<decimal> RATE_UOM { get; set; }
    }
}
