//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EPAEntities : DbContext
    {
        public EPAEntities()
            : base("name=EPAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<COMPANy> COMPANIES { get; set; }
        public DbSet<COMPANY_SUPPLIERS> COMPANY_SUPPLIERS { get; set; }
        public DbSet<PRICE_LIST_ITEM_TYPES> PRICE_LIST_ITEM_TYPES { get; set; }
        public DbSet<SUPPLIER> SUPPLIERS { get; set; }
    }
}
