//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyDllTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRICE_LIST_ITEM_TYPES
    {
        public string ITEM_TYPE { get; set; }
        public string ITEM_TYPE_GROUP { get; set; }
        public string PROP_TITLE_1 { get; set; }
        public string PROP_TITLE_2 { get; set; }
        public string PROP_TITLE_3 { get; set; }
        public string PROP_TITLE_4 { get; set; }
        public string PROP_TITLE_5 { get; set; }
        public string PROP_TITLE_6 { get; set; }
        public int PRICE_LIST_ID { get; set; }
    }
}
